In [1]:
import numpy as np

Array Creation

In [2]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Sum of all elements in the array

In [3]:
addition = np.sum(arr)
print(addition)

210


Mean of the elements 

In [4]:
avg = np.mean(arr)
print(avg)

10.5


Median of the elements

In [5]:
middle = np.median(arr)
print(middle)

10.5


Standard deviation

In [6]:
std_dev = np.std(arr)
print(std_dev)

5.766281297335398


Index of Numbers greater then 10

In [7]:
indices = np.where(arr > 10)
print(indices)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


2D Array Creation

In [8]:
arr2 = np.arange(1,17).reshape(4,4)

In [9]:
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


The transpose swaps rows and columns

In [10]:
tr_arr2 = np.transpose(arr2)
print (tr_arr2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [11]:
sum_row = np.sum(arr2 ,axis = 0)
print (sum_row)

[28 32 36 40]


Coloum wise Sum

In [12]:
sum_colo = np.sum(arr2,axis = 1)
print (sum_colo)

[10 26 42 58]


Array With Random Numbers

In [13]:
arr3_1 = np.random.randint(1, 21, size=(3, 3))
print(arr3_1)

[[10 10  9]
 [12  5  1]
 [ 9  7  3]]


In [14]:
arr3_2 = np.random.randint(1, 21, size=(3, 3))
print(arr3_2)

[[19 13 16]
 [13 10 10]
 [ 2  5 17]]


Add element wise

In [15]:
add_arr = arr3_1 + arr3_2
print(add_arr)

[[29 23 25]
 [25 15 11]
 [11 12 20]]


Substract element wise

In [16]:
sub_arr = arr3_1 - arr3_2
print(sub_arr)

[[ -9  -3  -7]
 [ -1  -5  -9]
 [  7   2 -14]]


Multipication

In [17]:
mul_arr = arr3_1 * arr3_2
print(mul_arr)

[[190 130 144]
 [156  50  10]
 [ 18  35  51]]


Dop Product

In [18]:
pro_arr = np.dot(arr3_1,arr3_2)
print(pro_arr)

[[338 275 413]
 [295 211 259]
 [268 202 265]]


In [19]:
arr1 = np.arange(1,13)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Reshape

In [20]:
arr1_2 = np.reshape(arr1,(3,4))
print(arr1_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Slicesing

In [21]:
sliced_arr = arr1_2[:2, -2:]
print(sliced_arr)

[[3 4]
 [7 8]]
